#api:
#    resource: "@ApiBundle/Controller/"
#    type:     annotation
#    prefix:   /

api:
    resource: "@ApiBundle/Controller/"
    type:     rest
    prefix:   /

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

# app/config/routing.yml
#app.swagger:
#    path: /api/doc.json
#    methods: GET
#    defaults: { _controller: nelmio_api_doc.controller.swagger }


NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

api_login_check:
    path: /api/login_check

