<?php

namespace ApiBundle\Repository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPendingProducts()
    {
        $queryBuilder = $this->createQueryBuilder('products')
                        ->where('products.status  = :status')
                        ->setParameter('status', "pending")
                        ->getQuery()
                        ->execute();

        return $queryBuilder;
    }
}
